# Generated by Django 3.1 on 2020-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
